apiVersion: v1
kind: Secret
metadata:
  name: testlinux
  labels:
    app: macbook
type: Opaque
data:
  {{- range $name, $value := .Values.data }}
  {{- if not (empty $value) }}
    {{ $name }}: {{ $value | b64enc | quote }}
  {{- end}}
  {{- end }}

